### Create Heatmaps for Weather Parameters

Creating heatmaps is going to be easy and fun. We'll feel like software developers when we add information to geological maps and can visualize the data based on density. The amount of coding needed to create a heatmap is small. For a basic heatmap, all we need to do is provide the following:

- Latitudes and longitudes for the locations
- A measurement value for each latitude and longitude in the form of arrays that have the same number of items in each array

Begin by importing our dependencies and Google API key, and then add our cities.csv file to a DataFrame. Create a new Jupyter Notebook file named VacationPy.ipynb. In the first cell, add our dependencies and API key.

In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

Let's review how we will use our dependencies. 
- We'll use Pandas to read our CSV file and create the locations and measurements from the DataFrame. 
- We'll use gmaps and the API key to create heatmaps and the locations map, 
- and we'll use the requests dependency to make a request to the Google Places JSON file. This will allow us to get hotel locations from the latitude and longitude of the city.

Next, we'll read our cities.csv file into a DataFrame.

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Marsh Harbour,BS,2022-07-12 20:29:44,26.5412,-77.0636,85.14,72,37,12.01
1,1,Yellowknife,CA,2022-07-12 20:28:12,62.4560,-114.3525,72.12,60,75,17.27
2,2,Punta Arenas,CL,2022-07-12 20:29:44,-53.1500,-70.9167,33.82,100,100,6.91
3,3,Limbang,MY,2022-07-12 20:29:44,4.7500,115.0000,78.06,98,100,2.44
4,4,Nioro,GM,2022-07-12 20:29:45,13.3500,-15.7500,84.40,71,89,10.29

One caveat to using gmaps: The data we use for any mapping must be either an integer or a floating-point decimal number. Let's check the data types for the columns of our DataFrame.

REWIND
Recall that you use the dtypes method to get the data types of a DataFrame.

Confirm the data types for the data columns are integers or floating-point decimal numbers.

In [3]:
# get the data types
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

### Create a Maximum Temperature Heatmap

First, tell gmaps to use your API key. You only need to configure gmaps to use your API key once.

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

Next, create the heatmap for the maximum temperature. The general syntax for creating a heatmap is as follows.

/1. Assign the locations to an array of latitude and longitude pairs.
locations = [latitude, longitude]

/2. Assign the weights variable to some values.
temperatures = # an array of length equal to the locations array length

/3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure()

/4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)

/5. Add the heatmap layer.
fig.add_layer(heatmap_layer)

/6. Call the figure to plot the data.
fig

Add the locations array and the values from the maximum temperature from our city_data_df DataFrame for Steps 1 and 2 and the rest of the code above.

In [5]:
# Get the maximum temperature. 
# To remove the negative temperatures we can use a for loop to iterate thru
# the max_temp and add the temperatures that are greater than 0 Â°F to a new list.

##max_temp = city_data_df["Max Temp"]
##temps = []
##for temp in max_temp:
##    temps.append(max(temp, 0))
    
# In the for loop, we're using the max() function to get the largest value
# between the temp and 0. If the temp is less than 0, then 0 will be added
# to the list in its place. Otherwise, the temp is added to the list.

# commenting out the for loop because added list comprehension in the
# heat layer section of the below code

Google heatmaps do not plot negative numbers. If you have a maximum temperature that is less than 0 Â°F, then you will get an InvalidWeightException error for this line of code:

    heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)

To remove the negative temperatures we can use a for loop to iterate through the max_temp and add the temperatures that are greater than 0 Â°F to a new list.

Add a new cell above our previous code block, and then add the following code in the cell and run the cell.

/Get the maximum temperature.

    max_temp = city_data_df["Max Temp"]
    temps = []
    for temp in max_temp:
        temps.append(max(temp, 0))
        
In the for loop, we're using the max() function to get the largest value between the temp and 0. If the temp is less than 0, then 0 will be added to the list in its place. Otherwise, the temp is added to the list.

Now change the following code in the heat_layer:

    heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)

To look like the following:

    heat_layer = gmaps.heatmap_layer(locations, weights=temps)

Instead of using the for loop, we can perform a list comprehension within the heatmap_layer() function.

Replace temps with our code for the list comprehension so our heat_layer code looks like the following:

    heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])

### Adjust Heatmap Zoom, Intensity, and Point Radius

This map is too large. We will need to make some adjustments to the gmaps.figure() attribute

First, add the geographic center of Earth in the form of latitude and longitude (30.0Â° N and 31.0Â° E). Also, add a zoom level so that only one map of Earth is shown.

When we add a center and zoom level to the gmaps.figure() attribute, it will look like this:

    fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

You might have to play with the zoom level to get things right.

When we run the cell, our map is centered and shows all the inhabitable places on Earth.

If we scroll and zoom in on North America, we can see that the circles for the temperatures need to be modified so that they are larger and show temperature gradient differences.
If you review the gmaps documentation, you may notice there is a dissipation option for creating heatmaps that can be added to the gmaps.heat_layer() attribute.

The options for this are:

1. The default option for the dissipation is "True," so we need to set our "dissipation" to "False."
2. We can add max_intensity to make each measurement have a better gradient variance.
3. We can add point_radius to make each measurement radius larger.

Also, you'll have to tweak these values until you are satisfied with the final map.

Let's modify our gmaps.heat_layer() attribute to heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4) and rerun our code.

In [6]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]

# Assign the figure variable.
##fig = gmaps.figure()
# add the geographic center of Earth in the form of lat/long (30.0Â° N and 31.0Â° E)
# Also, add a zoom level so that only one map of Earth is shown.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.
##heat_layer = gmaps.heatmap_layer(locations, weights=temps)
# edit: weights=max_temp to weights=temps after adding above for loop
# instead of using the for loop above, use list comprehension:
##heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# add false dissipation, max intensity for better gradient variance and
# point radius fo make radius measurement larger
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

### Create a Percent Humidity Heatmap

Now that we have created our maximum temperature heatmap, let's create the heatmap for humidity. We can reuse the code and use the humidity values for the measurements.

In [7]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

### Create a Percent Cloudiness Heatmap

Next, we will create the heatmap for percent cloudiness.

To create the heatmap for percent cloudiness, replace the measurement from the humidity values to cloudiness values. Copy the code that created the previous heatmap and edit your code with the line clouds = city_data_df["Cloudiness"] so that the percent cloudiness replaces the percent humidity, and set the variable weights=clouds, and run your cell.

In [8]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

### Create a Wind Speed Heatmap

Now we can create the final heatmap. Copy the code that created the previous heatmap and edit your code with the line wind = city_data_df["Wind Speed"] so that the wind speed replaces the percent cloudiness, and set the variable weights=wind, and run your cell.

In [9]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

### Get Vacation Criteria

Now, the cherry on top of the project: a feature on the app that allows customers to search for locations they want to travel based on their temperature preferences. Your clients will enter their preferences. Your code will tell them where to travel. It's beautiful, simple, and just needs a few more lines of code to actually work.

For the app we are creating, we need to prompt the user to enter the minimum and maximum temperature ranges as floating-point decimal numbers to filter the city_data_df DataFrame.

REWIND
Recall that you use the input() statement to prompt a user to enter information. To convert the input to a floating-point decimal number, wrap the input() statement with the float() method, like this: float(input()).

In a new cell, we'll write two input statements for the app that will prompt the customer to add minimum and maximum temperature values and convert these values to floating-point decimals.

The statement can be whatever you want it to be, but for our app, we'll prompt the customer with the following two input statements. When we run this cell, the customer will be prompted to enter the minimum temperature.

In [10]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

Next, filter the maximum temperature column in the city_data_df DataFrame using logical operators to create a new DataFrame with the cities that meet the customer's criteria.

REWIND
Recall that you use the loc[] method on the current DataFrame to create a new DataFrame from a current DataFrame. Inside the brackets, add the conditional filter.

The conditional filter will be city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"]>= min_temp. Also, filter the city_data_df DataFrame using the following statement.

The preferred_cities_df DataFrame will contain all the cities that meet the temperature criteria.

In [11]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Marsh Harbour,BS,2022-07-12 20:29:44,26.5412,-77.0636,85.14,72,37,12.01
3,3,Limbang,MY,2022-07-12 20:29:44,4.7500,115.0000,78.06,98,100,2.44
4,4,Nioro,GM,2022-07-12 20:29:45,13.3500,-15.7500,84.40,71,89,10.29
7,7,Albany,US,2022-07-12 20:29:46,42.6001,-73.9662,88.36,38,27,13.33
11,11,Ipora,BR,2022-07-12 20:29:47,-16.4419,-51.1178,84.51,26,59,4.07
12,12,Naze,JP,2022-07-12 20:29:47,28.3667,129.4833,76.12,89,90,6.42
15,15,Kapaa,US,2022-07-12 20:29:48,22.0752,-159.3190,82.38,78,100,13.80
16,16,Srandakan,ID,2022-07-12 20:29:48,-7.9386,110.2506,75.04,89,93,5.03
17,17,Hilo,US,2022-07-12 20:29:47,19.7297,-155.0900,85.28,72,75,10.36
19,19,Vaini,TO,2022-07-12 20:29:49,-21.2000,-175.2000,75.36,88,75,6.91

Before moving on, determine if the preferred_cities_df DataFrame has any null values for any of the rows.

can use any if the following:
- preferred_cities_df.count()
- preferred_cities_df.isnull().sum()
- preferred_cities_df.notnull().sum()

In [12]:
# check for null values
preferred_cities_df.count()

City_ID       208
City          208
Country       208
Date          208
Lat           208
Lng           208
Max Temp      208
Humidity      208
Cloudiness    208
Wind Speed    208
dtype: int64

IMPORTANT
Consider the following guidance:

1. Depending on the time of year and the seasons, you might have to adjust the minimum and maximum temperature to get enough cities.
2. It is a good idea to keep the number of cities to fewer than 200 to make it easier to plot the markers on the heatmap.
3. If you have some rows with null values, you'll need to drop them using the dropna() method at the end of your filtering statement when you are creating the new DataFrame.

### Map Vacation Criteria
Once the customers have filtered the database (DataFrame) based on their temperature preferences, show them a heatmap for the maximum temperature for the filtered cities. In addition, create a marker for each city that will display the name of the city, country code, maximum temperature, and name of a nearby hotel within three miles of the coordinates when the marker is clicked.

Using the coordinates from the preferred_cities_df DataFrame, find a hotel using our Google Places API and then retrieve that hotel information. Once we retrieve the hotel information, we'll need to store it so we can reference it and add the information to the pop-up marker.

### Get Travel Destinations

Don't add the hotel information to the preferred_cities_df DataFrame because this DataFrame is our filtered DataFrame, and the customer will always filter it for each trip. We'll need to create a new DataFrame specifically for the data needed to create a heatmap and pop-up markers.

Make a copy of the preferred_cities_df DataFrame and name it hotel_df. For the hotel_df, keep the columns "City," "Country," "Max Temp," "Lat," and "Lng." Add a new column to the hotel_df DataFrame to hold the name of the hotel.

Add the following code to a new cell and run it to create the hotel_df DataFrame, with an empty "hotel name" column

In [13]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

             City Country  Max Temp      Lat       Lng Hotel Name
0   Marsh Harbour      BS     85.14  26.5412  -77.0636
3         Limbang      MY     78.06   4.7500  115.0000
4           Nioro      GM     84.40  13.3500  -15.7500
7          Albany      US     88.36  42.6001  -73.9662
11          Ipora      BR     84.51 -16.4419  -51.1178
12           Naze      JP     76.12  28.3667  129.4833
15          Kapaa      US     82.38  22.0752 -159.3190
16      Srandakan      ID     75.04  -7.9386  110.2506
17           Hilo      US     85.28  19.7297 -155.0900
19          Vaini      TO     75.36 -21.2000 -175.2000

### Retrieve Hotels from a Nearby Search

Using the latitude and longitude and specific parameters, use the Google Places Nearby Search request to retrieve a hotel and add it to the Hotel Name column.

The first step for retrieving hotels from a Nearby Search is to set the parameters for the search.

#### Set the Parameters for a Nearby Search
To find the nearest establishment to geographic coordinates, use the Google Places Nearby Search request. First, navigate to the Nearby Search requests page (https://developers.google.com/maps/documentation/places/web-service/search#PlaceSearchRequests%0D%0A).

The Nearby Search request lets us perform these tasks:

1. Search for places within a specified area.
2. Refine the search using keywords and specifying the type of place we are searching for.
3. Use an API URL, where the output can be either XML or JSON format.

Although very similar to our OpenWeatherMap API search, with the Google Places Nearby Search, we'll add a specified area and keyword to search.

The documentation states we must provide specific parameters.

Specific parameters include:

1. Our API key
2. A location, which will be the latitude and longitude
3. A radius for the search. The radius can be up to 50,000 meters or approximately 31 miles. This distance is much too great for finding hotels, so we'll keep our search to 5,000 meters.
4. If we use the rankby=distance for a parameter, we need to add one or more of the three parameters above. We won't use the rankby=distance because we will be searching based on the radius from a given latitude and longitude.

We can add optional parameters such as a keyword, a type of business, or the name of a business.

For our hotel search, we'll use these parameters:

1. API key
2. Latitude and longitude
3. 5,000-meter radius
4. Type of place

To discover the support types we can use, click on the link "list of supported types" in the optional parameters list or navigate to the Place Types guide (https://developers.google.com/maps/documentation/places/web-service/supported_types).

On the webpage, Table 1 shows all the different Place types values. "Hotel" does not appear, but "lodging" does, so we will use the string "lodging" for the type parameter.

Next, we need to know how to add the other parameters in the search.

REWIND
Recall that when we made a request with the OpenWeatherMap API, we added the base URL with the city, city_url, to the request, city_weather = requests.get(city_url).

We can use the same format to make a request with the Google Places API. The following base URL is provided to retrieve the JSON format of the data:
https://maps.googleapis.com/maps/api/place/nearbysearch/json

Next, we'll need to look at the documentation on the Python Requests Library (https://requests.kennethreitz.org/en/latest/) provided earlier. The section "Passing Parameters In URLs" states that we can add the parameters as a dictionary of strings, using the params keyword argument requests.get('base URL', params=parameters).

In a new cell, add the parameters as key-value pairs. Add the params dictionary, API key, type, and radius parameters with the following values.

In [14]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key}

The g_key is our Google API key, so be sure to import the config.py file.

Next, add the coordinates for the location parameter for each city, which need to be pulled from the Lat and Lng columns of the hotel_df DataFrame. We'll need to iterate through the columns of the DataFrame and add the coordinates to the params dictionary before making the request and retrieving the JSON data. However, before iterating through the hotel_df DataFrame, we need to know what the JSON data looks like from a search. Let's practice using a fixed latitude and longitude so we understand where to get the hotel name.

### Iterate Through hotel_df DataFrame
We can use the iterrows() function to perform the iteration; however, we need to provide the index and the row in the for loop using this syntax: for index, row in df.iterrows().

In [16]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    ##hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    # this causes an "index error" to fix, use try-except block
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In this code, we modified how we add the coordinates to the location key. We add the latitude and longitude to the location using the f-string format. The rest of the code is the same as when we practiced, but at the end, we add the name of the first hotel to the Hotel Name column in the hotel_df DataFrame.

Let's run the cell and retrieve the data. Our output says there is an IndexError.

How would you handle the IndexError to get the code to run? a try-except block

REWIND
Recall that when trying to parse the data from an API request, we need to use a try-except block to handle the error with a statement and continue the retrieval.

Let's modify the last piece of code and make a try-except block to handle the IndexError. Edit the last piece of code so that it looks like the following.

/Grab the first hotel from the results and store the name.

    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

NOTE
If you encounter more errors, add them to the except blockâlike so, (IndexError, NewError)âand continue running your code until there are no errors.

In [17]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Marsh Harbour,BS,85.14,26.5412,-77.0636,Abaco Beach Resort
3,Limbang,MY,78.06,4.7500,115.0000,Purnama Hotel
4,Nioro,GM,84.40,13.3500,-15.7500,
7,Albany,US,88.36,42.6001,-73.9662,
11,Ipora,BR,84.51,-16.4419,-51.1178,OÃ¡sis Motel
12,Naze,JP,76.12,28.3667,129.4833,Shishime Hotel
15,Kapaa,US,82.38,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
16,Srandakan,ID,75.04,-7.9386,110.2506,Puri Brata
17,Hilo,US,85.28,19.7297,-155.0900,Hilo Hawaiian Hotel
19,Vaini,TO,75.36,-21.2000,-175.2000,Keleti Beach Resort

For more information, see the Google Developers' Nearby Search documentation (https://developers.google.com/maps/documentation/places/web-service/search#PlaceSearchRequests).

### Create a Maximum Temperature Heatmap from a Hotel DataFrame
Our final task will be to add pop-up markers with hotel information to a heatmap.

Before we add pop-up markers with hotel information, let's create a heatmap using the maximum temperature from our hotel_df DataFrame by reusing the code and changing the DataFrame name.

If we refer to the gmaps documentation on how to add markers (https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#markers-and-symbols), the syntax is 

    markers = gmaps.marker_layer(marker_locations)

where the marker_locations are latitudes and longitudes.

Let's add the markers for each city on top of the heatmap.

/Add a heatmap of temperature for the vacation spots.

    locations = hotel_df[["Lat", "Lng"]]
    max_temp = hotel_df["Max Temp"]
    fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
    heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, 
                 dissipating=False, max_intensity=300, point_radius=4)

/add markers & call the layer

    marker_layer = gmaps.marker_layer(locations)

    fig.add_layer(heat_layer)
    fig.add_layer(marker_layer)

/Call the figure to plot the data.

    fig

Now we can add a pop-up marker for each city that displays the hotel name, city name, country, and maximum temperature.

From the gmaps documentation on how to add markers (https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#markers-and-symbols), we need to add an info_box_template that has the following syntax.

    info_box_template = """
    <dl>
    <dt>Name</dt><dd>{column1}</dd>
    <dt>Another name</dt><dd>{column2}</dd>
    </dl>
    """

This is a new code block, so let's review its form and function.

First, the info_box_template variable is assigned to a multiline string using three quotes. The text inside the multiline string is HTML code. HTML code is defined by the opening and closing the angular brackets (e.g., < tag > and < tag />). Angular brackets always come in pairs. The opening angular bracket is followed by some text inside, such as dl, dt, and dd. The closing angular bracket is preceded by a forward-slash ("/"). The text inside with the angular brackets is called a tag. We'll see more examples of HTML code in an upcoming module.

Here's what these tags mean:

- The < dl > tag is a description list (dl).
- The < dt > tag is a term or name in a description list that is nested under the < dl > tag.
- The < dd > tag is used to define the term or name or < dt > tag.

    If we were to write out these tags on paper, it would look like this.

- Description List: < dl >
    - Description Term: < dt >
        - Description Definition: < dd >
    - Description Term: < dt >
        - Description Definition: < dd >

For our purposes, we'll add the hotel name, city name, country code, and the maximum temperature values from the hotel_df DataFrame as the description definition.

Next, add the data to the code by iterating through the hotel_df DataFrame using the iterrows() function. Then add the information to the gmaps.marker_layer() attribute with the locations.

According to the documentation (https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#markers-and-symbols), we can use this example to create the data for the info_box_template:

From the documentation, we can take this code:

    plant_info = [info_box_template.format(**plant) for plant in nuclear_power_plants]

Then edit this code by replacing "plant_info" with "hotel_info," and then use the iterrows() function to get the index and data in the row to add to the marker.

In [20]:
# add a pop-up marker for each city that displays the hotel name, city name,
# country, & max temp
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

Let's review what we're doing with this code.

1. We set the hotel_info equal to the info_box_content.
2. In the list comprehension, info_box_template.format(** row) for index, row in hotel_df.iterrows(), we iterate through each "row" of the hotel_df DataFrame and then format the info_box_template with the data we set to populate the from each row. Remember, we are not using every row; we are only using the rows defined in the info_box_template, which are Hotel Name, City, Country, and Max Temp.

Next, in the code we used to create the heatmap with markers, add info_box_content=hotel_info to the gmaps.marker_layer() attribute with the locations.

*pulled map code from 2 cells above down here, used md to the original cell

In [21]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, 
             dissipating=False, max_intensity=300, point_radius=4)

# add pop up markers & call the layers
##marker_layer = gmaps.marker_layer(locations)
# add info box
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))